### ISSUE TITLE
为什么只有接口没有实现？

### ISSUE THREAD

**Issue by jerrybendy** [fwolf/uuid.php#1]
why interface only?

**Comment by fwolf** [comment]
还在写……有了点新构思，想优化一下

**Comment by jerrybendy** [comment]
NODEJS 上面有一个 `node-uuid` 的项目，或许可以参考下 。另外，不知道 composer 上面有没有现成的 uuid 生成的项目

[https://github.com/broofa/node-uuid](https://github.com/broofa/node-uuid)

**Comment by fwolf** [comment]
@jerrybendy PHP 可以看看这个： https://packagist.org/packages/ramsey/uuid

我这里主要是 v1，也就是基于时间的，方便排序，优化数据库写入速度。

另外就是为了减少长度，用了一些特殊的转换，详细的在每个方法中将会有，
还会移植一个 benchmark 过来。

**Comment by jerrybendy** [comment]
哦，好吧，表示对这些东西还没什么研究  😁

**Comment by jerrybendy** [comment]
这个写得太专业了，居然没看懂 :grin:

**Comment by fwolf** [comment]
有demo！使用的话用composer就好嘛。
